server:
  port: 8084

spring:
  application:
    name: msvc-division
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/division_db
    username: root
    password: root
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: division_db

#Configurando cliente a eureka
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka